version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  # Alternativa com imagem pré-construída
  backend-alternative:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3002:3001"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    command: sh -c "npm install && npm run build && npm start"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
